pipeline {
    agent any
    tools {
        jdk 'jdk17'
        nodejs 'node20'
    }
    environment {
        SCANNER_HOME = tool 'sonar-scanner'
        DOCKERHUB_CREDENTIALS = credentials('dockerhub')
        DOCKER_IMAGE = 'dahunsij/ejobs_backend'
        DOCKER_NETWORK = 'ejobs_network'
        CONTAINER_NAME = 'ejobs_backend'
    }
    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }
        stage('Clone Repository') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'GIT_PAT', usernameVariable: 'GITHUB_USER', passwordVariable: 'GITHUB_PASS')]) {
                        sh 'git clone https://${GITHUB_USER}:${GITHUB_PASS}@github.com/Essentialng/ejobs.git'
                        sh 'cd ejobs && git checkout main'
                    }
                }
            }
        }
        stage('Read and Increment Version') {
            steps {
                script {
                    def version = readFile('ejobs/backend/version.txt').trim()
                    def parts = version.tokenize('.')
                    parts[2] = (parts[2].toInteger() + 1).toString()
                    def newVersion = parts.join('.')
                    writeFile(file: 'ejobs/backend/version.txt', text: newVersion)
                    sh 'cd ejobs && git add backend/version.txt && git commit -m "Update version to ${newVersion}" && git push'
                    env.BUILD_VERSION = newVersion
                }
            }
        }
        stage('SonarQube Analysis') {
            steps {
                dir('ejobs/backend') {
                    withSonarQubeEnv('SonarQube-Servers') {
                        sh '''
                        $SCANNER_HOME/bin/sonar-scanner -Dsonar.projectName=ejobs_backend-CICD \
                        -Dsonar.projectKey=ejobs_backend-CICD \
                        -X
                        '''
                    }
                }
            }
        }
        stage('Quality Gate') {
            steps {
                script {
                    waitForQualityGate abortPipeline: false, credentialsId: 'SonarQube-Token'
                }
            }
        }
        stage('Install Dependencies') {
            steps {
                dir('ejobs/backend') {
                    sh "npm install"
                }
            }
        }
        stage('TRIVY FS Scan') {
            steps {
                dir('ejobs/backend') {
                    sh "trivy fs . > trivyfs.txt"
                }
            }
        }
        stage('Docker Build & Push') {
            steps {
                dir('ejobs/backend') {
                    script {
                        docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
                            sh "docker build -t ${DOCKER_IMAGE}:latest -f Dockerfile ."
                            sh "docker tag ${DOCKER_IMAGE}:latest ${DOCKER_IMAGE}:${env.BUILD_VERSION}.RELEASE"
                            sh "docker push ${DOCKER_IMAGE}:${env.BUILD_VERSION}.RELEASE"
                        }
                    }
                }
            }
        }
        stage('TRIVY Image Scan') {
            steps {
                sh "trivy image ${DOCKER_IMAGE}:${env.BUILD_VERSION}.RELEASE > trivyimage.txt"
            }
        }
        stage('Deploy to VM') {
            steps {
                sshagent(['vm-ssh-credentials']) {
                    sh '''
                    ssh DevSecOps_Admin@13.92.179.121 "docker pull ${DOCKER_IMAGE}:${BUILD_VERSION}.RELEASE && docker stop ${DOCKER_IMAGE} || true && docker rm ${DOCKER_IMAGE} || true && docker run -d -p 4000:4000 --name ${DOCKER_IMAGE} ${DOCKER_IMAGE}:${BUILD_VERSION}.RELEASE"
                    '''
                }
            }
        }
    }
}
